version: "3"

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - jenkinsHome:/var/jenkins_home

volumes:
  jenkinsHome:
